from daps_webui import db


class Settings(db.Model):
    __tablename__ = "settings_table"
    id = db.Column(db.Integer, primary_key=True)
    log_level_unmatched_assets = db.Column(db.String, default="info", nullable=False)
    log_level_poster_renamer = db.Column(db.String, default="info", nullable=False)
    log_level_plex_uploaderr = db.Column(db.String, default="info", nullable=False)
    log_level_border_replacerr = db.Column(db.String, default="info", nullable=False)
    poster_renamer_schedule = db.Column(db.String, nullable=True)
    unmatched_assets_schedule = db.Column(db.String, nullable=True)
    plex_uploaderr_schedule = db.Column(db.String, nullable=True)
    target_path = db.Column(db.String, nullable=True)
    source_dirs = db.Column(db.String, nullable=True)
    library_names = db.Column(db.String, nullable=True)
    instances = db.Column(db.String, nullable=True)
    asset_folders = db.Column(db.Integer, default=0, nullable=False)
    clean_assets = db.Column(db.Integer, default=0, nullable=False)
    unmatched_assets = db.Column(db.Integer, default=1, nullable=False)
    replace_border = db.Column(db.Integer, default=0, nullable=False)
    border_setting = db.Column(db.String, nullable=True)
    custom_color = db.Column(db.String, nullable=True)
    run_single_item = db.Column(db.Integer, default=0, nullable=False)
    only_unmatched = db.Column(db.Integer, default=0, nullable=False)
    upload_to_plex = db.Column(db.Integer, default=0, nullable=False)
    match_alt = db.Column(db.Integer, default=0, nullable=False)
    reapply_posters = db.Column(db.Integer, default=0, nullable=False)
    show_all_unmatched = db.Column(db.Integer, default=0, nullable=False)
    disable_unmatched_collections = db.Column(db.Integer, default=0, nullable=False)
