"""add arr_id to unmatched items

Revision ID: 0169a2a8a09a
Revises: e684a2412f9e
Create Date: 2025-01-06 09:02:56.216686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0169a2a8a09a'
down_revision = 'e684a2412f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arr_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arr_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.drop_column('arr_id')

    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.drop_column('arr_id')

    # ### end Alembic commands ###
