"""add custom_color setting to file_cache

Revision ID: 16b0ad839532
Revises: 65780ec45786
Create Date: 2024-12-30 10:12:41.877985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b0ad839532'
down_revision = '65780ec45786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_setting', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('custom_color', sa.String(), nullable=True))
        batch_op.drop_column('border_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_color', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('custom_color')
        batch_op.drop_column('border_setting')

    # ### end Alembic commands ###
