"""add gdrive + rclone model

Revision ID: 51fd33f18615
Revises: 3e5915a6bca0
Create Date: 2025-02-04 17:44:23.812086

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51fd33f18615"
down_revision = "3e5915a6bca0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gdrives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("drive_name", sa.String(), nullable=True),
        sa.Column("drive_id", sa.String(), nullable=True),
        sa.Column("drive_location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rclone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("rclone_token", sa.String(), nullable=True),
        sa.Column("rclone_secret", sa.String(), nullable=True),
        sa.Column("service_account", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "log_level_drive_sync",
                sa.String(),
                server_default="info",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("drive_sync_schedule", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.drop_column("drive_sync_schedule")
        batch_op.drop_column("log_level_drive_sync")

    op.drop_table("rclone")
    op.drop_table("gdrives")
    # ### end Alembic commands ###
