"""rename border_color to border_setting

Revision ID: 65780ec45786
Revises: a80b2e94fe6d
Create Date: 2024-12-30 10:06:43.597252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65780ec45786'
down_revision = 'a80b2e94fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_setting', sa.String(), nullable=True))
        batch_op.drop_column('border_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_color', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('border_setting')

    # ### end Alembic commands ###
