"""add only_unmatched flag to settings

Revision ID: 980babe10698
Revises: fc239285fcff
Create Date: 2025-01-11 12:36:57.079340

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "980babe10698"
down_revision = "fc239285fcff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "only_unmatched", sa.Integer(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.drop_column("only_unmatched")

    # ### end Alembic commands ###
