"""add hex code setting

Revision ID: a80b2e94fe6d
Revises: b6c35bb19a0b
Create Date: 2024-12-29 18:19:15.523486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80b2e94fe6d'
down_revision = 'b6c35bb19a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.drop_column('custom_color')

    # ### end Alembic commands ###
