"""Add gdrive + rclone model

Revision ID: e6f108da948c
Revises: 3e5915a6bca0
Create Date: 2025-01-31 18:44:06.960323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f108da948c'
down_revision = '3e5915a6bca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdrives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_name', sa.String(), nullable=True),
    sa.Column('drive_id', sa.String(), nullable=True),
    sa.Column('drive_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rclone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('rclone_token', sa.String(), nullable=True),
    sa.Column('rclone_secret', sa.String(), nullable=True),
    sa.Column('service_account', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rclone')
    op.drop_table('gdrives')
    # ### end Alembic commands ###
