"""add drive sync toggle for renamer

Revision ID: ef27b2b69de8
Revises: d52032a429f3
Create Date: 2025-02-17 10:57:27.860767

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef27b2b69de8"
down_revision = "d52032a429f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("drive_sync", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings_table", schema=None) as batch_op:
        batch_op.drop_column("drive_sync")

    # ### end Alembic commands ###
