"""add instance to unmatched movies/shows

Revision ID: fc239285fcff
Revises: 0169a2a8a09a
Create Date: 2025-01-11 10:55:59.284429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc239285fcff'
down_revision = '0169a2a8a09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance', sa.String(), nullable=True))

    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.drop_column('instance')

    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.drop_column('instance')

    # ### end Alembic commands ###
